# Generated by Django 3.1.1 on 2020-09-09 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabelname', models.CharField(max_length=64)),
                ('remark', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(blank=True, db_column='UserId', primary_key=True, serialize=False)),
                ('usertype', models.CharField(blank=True, db_column='UserType', max_length=64, null=True)),
                ('username', models.CharField(blank=True, db_column='Username', max_length=64, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=64, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=64, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=64, null=True)),
                ('createdate', models.DateField(blank=True, db_column='CreateDate', null=True)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
